version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
        - "-SA1029"
        - "-ST1005"
        - "-ST1016"
    gosec:
      excludes:
        - G101
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
