image: golang:1.14

definitions:
  steps:
    - step: &test-definition-v1
        name: Build and test (v1)
        script:
          - go build

          # Style checks
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
          - ./bin/golangci-lint run

          # Build and test
          - go test -v -cover -race .
    - step: &test-definition-v2
        name: Build and test (v2)
        script:
          - cd v2
          - go build

          # Style checks
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
          - ./bin/golangci-lint run

          # Build and test
          - go test -v -cover -race .

    - step: &go-mod-tag
        name: Tag
        script:
          - export NEXT_VERSION=$(git fetch --unshallow --tags && git describe --tags --abbrev=0 | awk -F. -v OFS=. '{$2 += 1 ; print}')
          - echo "\n***** Applying version tag ${NEXT_VERSION} *****"
          - git tag -a -m "[skip ci] Tagging with build version" "${NEXT_VERSION}"
          - git push origin ${NEXT_VERSION}

pipelines:
  default:
    - parallel:
      - step:
          <<: *test-definition-v1
      - step:
          <<: *test-definition-v2
  branches:
    master:
    - parallel:
      - step:
          <<: *test-definition-v1
      - step:
          <<: *test-definition-v2
    - step:
        <<: *go-mod-tag
        name: Version


