image: golang:1.26

definitions:
  steps:
    - step: &test-definition
        name: Build and test
        script:
          - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v2.11.4
          - make test

    - step: &go-mod-tag
        name: Tag
        script:
          - export NEXT_VERSION=$(git fetch --unshallow --tags && git describe --tags --abbrev=0 | awk -F. -v OFS=. '{$2 += 1 ; print}')
          - echo "\n***** Applying version tag ${NEXT_VERSION} *****"
          - git tag -a -m "[skip ci] Tagging with build version" "${NEXT_VERSION}"
          - git push origin ${NEXT_VERSION}

pipelines:
  default:
    - step:
        <<: *test-definition
  branches:
    master:
    - step:
        <<: *test-definition
    - step:
        <<: *go-mod-tag
        name: Version

