// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aws/aws-sdk-go/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretsManagerAPI creates a new instance of SecretsManagerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsManagerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsManagerAPI {
	mock := &SecretsManagerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretsManagerAPI is an autogenerated mock type for the SecretsManagerAPI type
type SecretsManagerAPI struct {
	mock.Mock
}

type SecretsManagerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretsManagerAPI) EXPECT() *SecretsManagerAPI_Expecter {
	return &SecretsManagerAPI_Expecter{mock: &_m.Mock}
}

// GetSecretValue provides a mock function for the type SecretsManagerAPI
func (_mock *SecretsManagerAPI) GetSecretValue(getSecretValueInput *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error) {
	ret := _mock.Called(getSecretValueInput)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 *secretsmanager.GetSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error)); ok {
		return returnFunc(getSecretValueInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*secretsmanager.GetSecretValueInput) *secretsmanager.GetSecretValueOutput); ok {
		r0 = returnFunc(getSecretValueInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*secretsmanager.GetSecretValueInput) error); ok {
		r1 = returnFunc(getSecretValueInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerAPI_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type SecretsManagerAPI_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - getSecretValueInput
func (_e *SecretsManagerAPI_Expecter) GetSecretValue(getSecretValueInput interface{}) *SecretsManagerAPI_GetSecretValue_Call {
	return &SecretsManagerAPI_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue", getSecretValueInput)}
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) Run(run func(getSecretValueInput *secretsmanager.GetSecretValueInput)) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*secretsmanager.GetSecretValueInput))
	})
	return _c
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) Return(getSecretValueOutput *secretsmanager.GetSecretValueOutput, err error) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Return(getSecretValueOutput, err)
	return _c
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) RunAndReturn(run func(getSecretValueInput *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error)) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}
